sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo service memcached stop
  - sudo apt-get install -y libgoogle-perftools-dev
script:
  - make -j 2
  - ./yrmcdsd &
  - sleep 1
  - make -j 2 tests
  - ./test/protocol_binary.exe localhost
